# Generated by Django 6.0.5 on 2026-05-26 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Flat File Export'), ('UTILITY', 'Utility Portal CSV'), ('CONCUR', 'SAP Concur API Payload')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUSPICIOUS', 'Suspicious'), ('APPROVED', 'Approved')], default='PENDING', max_length=15)),
                ('scope_category', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=1)),
                ('source_row_identifier', models.CharField(max_length=100)),
                ('activity_type', models.CharField(max_length=255)),
                ('raw_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Original value from source payload', max_digits=15, null=True)),
                ('raw_unit', models.CharField(blank=True, help_text='Original unit (e.g., Liters, Gallons, IATA_Pair)', max_length=50, null=True)),
                ('normalized_quantity_kwh', models.DecimalField(decimal_places=4, help_text='Unified internal normalization footprint', max_digits=15)),
                ('flags_meta', models.JSONField(blank=True, default=dict, help_text='Stores unstructured system parsing errors, warnings, and payload captures')),
                ('is_locked', models.BooleanField(default=False, help_text='True immediately when an analyst signs off; completely immutabilizes the record')),
                ('is_edited', models.BooleanField(default=False, help_text='Tracks whether the row was programmatically ingested or manually adjusted')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp of analyst validation', null=True)),
                ('approved_by', models.CharField(blank=True, help_text='Footprint signature of verifying analyst', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.ingestionbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ingestion.tenant')),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
