# Generated by Django 6.0.5 on 2026-05-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_auto_20260526_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='migration_trigger',
            field=models.CharField(default='sync', max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='flags_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='normalized_quantity_kwh',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='raw_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='raw_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
